apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: knowledge-base
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # You can adjust the size
  storageClassName: standard # IMPORTANT: Replace with your StorageClass
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: knowledge-base
spec:
  serviceName: "minio-service"
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        command:
        - /bin/bash
        - -c
        - minio server /data --console-address :9001
        envFrom:
        - secretRef:
            name: knowledge-base-secrets
        ports:
        - containerPort: 9000
        - containerPort: 9001
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard # IMPORTANT: Replace with your StorageClass
      resources:
        requests:
          storage: 10Gi # You can adjust the size
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: knowledge-base
spec:
  ports:
  - port: 9000
    targetPort: 9000
    name: api
  - port: 9001
    targetPort: 9001
    name: console
  selector:
    app: minio
