apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-pvc
  namespace: knowledge-base
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # You can adjust the size
  storageClassName: standard # IMPORTANT: Replace with your StorageClass
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  namespace: knowledge-base
spec:
  serviceName: "qdrant-service"
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant:latest
        ports:
        - containerPort: 6333
        - containerPort: 6334
        volumeMounts:
        - name: data
          mountPath: /qdrant/storage
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard # IMPORTANT: Replace with your StorageClass
      resources:
        requests:
          storage: 5Gi # You can adjust the size
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
  namespace: knowledge-base
spec:
  ports:
  - port: 6333
    targetPort: 6333
    name: grpc
  - port: 6334
    targetPort: 6334
    name: http
  selector:
    app: qdrant
