apiVersion: apps/v1
kind: Deployment
metadata:
  name: reranker-service
  namespace: knowledge-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reranker-service
  template:
    metadata:
      labels:
        app: reranker-service
    spec:
      imagePullSecrets:
      - name: regcred # IMPORTANT: Replace with your image pull secret
      nodeSelector:
        nvidia.com/gpu: "true" # IMPORTANT: Ensure this label matches your GPU nodes
      # tolerations:
      # - key: "nvidia.com/gpu"
      #   operator: "Exists"
      #   effect: "NoSchedule"
      containers:
      - name: reranker-service
        image: your-docker-registry/your-repo/reranker-service:latest # IMPORTANT: Replace with your image path
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: knowledge-base-config
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "8Gi"
            cpu: "2"
          requests:
            nvidia.com/gpu: 1
            memory: "4Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: reranker-service
  namespace: knowledge-base
spec:
  selector:
    app: reranker-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
